// <auto-generated />
namespace magnets.repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v110 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v110));
        
        string IMigrationMetadata.Id
        {
            get { return "201712030639553_v1.10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
